function escapeHtml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;")
}

export function renderHomePage(input: { ready: boolean; version: string }): string {
  const version = escapeHtml(input.version)
  return `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>OpenCode Control Plane</title>
  <style>
    :root { color-scheme: dark; font-family: Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background:#0a0d12; color:#edf0f5; --panel:#11151b; --panel2:#171c24; --line:#252c35; --muted:#929ba9; --muted2:#687280; --accent:#5b8def; --success:#43c58a; --warning:#f0b95a; --danger:#ef6a7a; }
    * { box-sizing:border-box; } html,body { height:100%; } body { margin:0; overflow:hidden; background:radial-gradient(circle at 45% -20%,#1d2142 0,transparent 38%),#080b12; } button,input,textarea { font:inherit; } button { cursor:pointer; } button:disabled { opacity:.5; cursor:wait; }
    .app { height:100%; display:grid; grid-template-rows:58px minmax(0,1fr); }
    .topbar { display:flex; align-items:center; justify-content:space-between; padding:0 18px; border-bottom:1px solid var(--line); background:#0b0e16e8; backdrop-filter:blur(16px); }
    .brand { display:flex; align-items:center; gap:11px; font-weight:680; letter-spacing:-.02em; } .brand small { color:var(--muted); font-weight:500; margin-left:4px; }
    .brand-mark { display:grid; place-items:center; width:30px; height:30px; border-radius:9px; background:#e9edf5; color:#11151b; box-shadow:0 8px 24px #0006; font-size:12px; }
    .server-pill,.agent-state { display:inline-flex; align-items:center; gap:8px; border:1px solid var(--line); border-radius:999px; padding:6px 10px; color:var(--muted); background:#111621; font-size:12px; }
    .dot { width:7px; height:7px; border-radius:50%; background:var(--muted2); } .dot.ready,.dot.IDLE,.dot.READY { background:var(--success); box-shadow:0 0 0 4px #43c58a18; } .dot.RUNNING,.dot.CREATING { background:#9b8cff; box-shadow:0 0 0 4px #9b8cff18; animation:pulse 1.2s infinite; } .dot.WAITING_APPROVAL { background:var(--warning); } .dot.FAILED,.dot.CANCELLED { background:var(--danger); }
    @keyframes pulse { 50% { opacity:.42; transform:scale(.8); } }
    .shell { min-height:0; display:grid; grid-template-columns:286px minmax(440px,1fr) 316px; } .sidebar,.rightbar { min-height:0; overflow:auto; background:#0d111aef; } .sidebar { border-right:1px solid var(--line); } .rightbar { border-left:1px solid var(--line); }
    .section { padding:16px; border-bottom:1px solid var(--line); } .section-head { display:flex; align-items:center; justify-content:space-between; gap:10px; margin-bottom:11px; } .eyebrow { color:var(--muted); font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.09em; }
    .icon-button { display:grid; place-items:center; width:30px; height:30px; padding:0; border:1px solid var(--line); border-radius:8px; color:var(--muted); background:var(--panel2); } .icon-button:hover { color:white; border-color:#3a4358; }
    input,textarea { width:100%; color:#eef0f7; background:#0b0f14; border:1px solid var(--line); border-radius:10px; outline:none; padding:10px 11px; resize:none; } input:focus,textarea:focus { border-color:#497edb; box-shadow:0 0 0 3px #5b8def1b; }
    .primary,.soft,.danger-button { border-radius:9px; padding:9px 12px; color:white; font-weight:620; } .primary { border:1px solid #6e9bf0; background:#5b8def; box-shadow:0 7px 18px #234d9438; } .primary:hover { background:#6a99f2; } .soft { background:#1a2030; color:#bdc4d4; border:1px solid var(--line); } .danger-button { background:#351a24; color:#ff9aaa; border:1px solid #5b2835; } .wide { width:100%; margin-top:8px; }
    .task-list,.agent-list { display:grid; gap:6px; } .task-item,.agent-item { width:100%; text-align:left; color:inherit; background:transparent; border:1px solid transparent; border-radius:10px; } .task-item:hover,.agent-item:hover { background:#171c24; } .task-item.active,.agent-item.active { background:#17243a; border-color:#2c4f83; }
    .task-item { display:flex; gap:10px; align-items:center; padding:9px; } .task-icon { display:grid; place-items:center; width:30px; height:30px; flex:0 0 auto; border-radius:8px; background:#1f2432; color:#b4bbcb; font-size:11px; } .task-copy { min-width:0; flex:1; } .task-title { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-size:13px; font-weight:620; } .task-meta { margin-top:3px; color:var(--muted2); font-size:11px; }
    .agent-item { display:grid; grid-template-columns:32px minmax(0,1fr) auto; gap:9px; align-items:center; padding:8px; } .avatar { display:grid; place-items:center; width:32px; height:32px; border-radius:10px; background:#222a35; color:#c5cada; font-size:10px; font-weight:750; } .avatar.MAIN { color:#bcd3ff; background:#1d3152; } .agent-name { font-size:13px; font-weight:620; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; } .agent-role { color:var(--muted2); font-size:11px; margin-top:2px; }
    .count,.question-count { min-width:21px; height:21px; display:inline-grid; place-items:center; padding:0 6px; border-radius:999px; background:#233c63; color:#c4d8ff; font-size:10px; } details summary { cursor:pointer; color:#b6bdcc; font-size:12px; }
    .chat { min-width:0; min-height:0; display:grid; grid-template-rows:64px minmax(0,1fr) auto; background:#0b0f17c9; } .chat-head { display:flex; align-items:center; justify-content:space-between; gap:14px; padding:0 20px; border-bottom:1px solid var(--line); background:#0e121cde; backdrop-filter:blur(12px); } .chat-title { min-width:0; } .chat-title h1 { margin:0; font-size:15px; font-weight:680; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; } .chat-title p { margin:4px 0 0; color:var(--muted2); font-size:11px; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; } .chat-actions { display:flex; align-items:center; gap:8px; }
    .messages { min-height:0; overflow-y:auto; padding:28px max(22px,calc((100% - 820px)/2)); scroll-behavior:smooth; } .welcome { max-width:560px; margin:13vh auto; text-align:center; color:var(--muted); } .welcome-mark { width:50px; height:50px; display:grid; place-items:center; margin:0 auto 16px; border-radius:15px; color:#d6d1ff; background:linear-gradient(145deg,#29244d,#191d2e); border:1px solid #38345c; } .welcome h2 { margin:0 0 8px; color:#e7e9f1; font-size:18px; } .welcome p { margin:0; font-size:13px; line-height:1.7; }
    .turn { display:grid; grid-template-columns:30px minmax(0,1fr); gap:11px; margin-bottom:24px; } .turn.user { grid-template-columns:minmax(0,1fr) 30px; } .turn.user .turn-body { order:1; justify-self:end; max-width:78%; } .turn.user .turn-avatar { order:2; background:#34385a; } .turn-avatar { width:30px; height:30px; display:grid; place-items:center; border-radius:9px; background:#27243e; color:#cfc9ff; font-size:9px; font-weight:780; } .turn-body { min-width:0; max-width:88%; } .turn-meta { display:flex; align-items:center; gap:8px; margin-bottom:6px; color:var(--muted2); font-size:10px; } .turn.user .turn-meta { justify-content:flex-end; }
    .bubble { color:#dfe3ec; font-size:13.5px; line-height:1.68; white-space:pre-wrap; overflow-wrap:anywhere; } .turn.user .bubble { padding:10px 13px; border-radius:14px 4px 14px 14px; color:white; background:#315f9f; box-shadow:0 8px 22px #173d712c; }
    .reasoning { margin-top:9px; color:var(--muted); font-size:12px; } .reasoning div { margin-top:7px; padding-left:10px; border-left:2px solid #343b4f; white-space:pre-wrap; }
    .tool-card { margin-top:9px; border:1px solid var(--line); border-radius:10px; overflow:hidden; background:#10151f; } .tool-head { display:flex; align-items:center; justify-content:space-between; gap:10px; padding:8px 10px; color:#c8ceda; background:#151a25; font-size:11px; font-weight:650; } .tool-status { color:var(--muted); font-weight:500; } .tool-status.completed { color:var(--success); } .tool-status.error { color:var(--danger); } .tool-detail { margin:0; padding:9px 10px; max-height:190px; overflow:auto; color:#9da6b9; white-space:pre-wrap; overflow-wrap:anywhere; font:10.5px ui-monospace,SFMono-Regular,Menlo,monospace; }
    .message-error { margin-top:8px; padding:9px 11px; border:1px solid #5a2935; border-radius:9px; color:#ff9aaa; background:#27131b; font-size:12px; white-space:pre-wrap; } .thinking { display:inline-flex; align-items:center; gap:6px; color:var(--muted); font-size:12px; } .thinking i { width:5px; height:5px; border-radius:50%; background:#9b8cff; animation:pulse 1s infinite; } .thinking i:nth-child(2) { animation-delay:.16s; } .thinking i:nth-child(3) { animation-delay:.32s; }
    .composer-wrap { padding:12px max(18px,calc((100% - 850px)/2)) 17px; background:linear-gradient(transparent,#0b0f17 25%); } .composer { border:1px solid #303844; border-radius:14px; background:#121820; box-shadow:0 14px 45px #00000035; overflow:hidden; } .composer:focus-within { border-color:#497edb; box-shadow:0 0 0 3px #5b8def16,0 14px 45px #00000035; } .composer textarea { min-height:72px; max-height:190px; border:0; border-radius:0; background:transparent; padding:13px 14px 8px; box-shadow:none; } .composer-foot { display:flex; align-items:center; justify-content:space-between; gap:12px; padding:8px 9px 9px 13px; color:var(--muted2); font-size:10px; } .send { min-width:72px; border:1px solid #6e9bf0; border-radius:9px; padding:8px 12px; color:white; background:#5b8def; font-weight:670; }
    .permission-list { display:grid; gap:9px; } .permission-item { padding:11px; border:1px solid var(--line); border-radius:11px; background:#111621; } .permission-title { display:flex; align-items:center; justify-content:space-between; gap:8px; font-size:12px; font-weight:660; } .risk { padding:3px 6px; border-radius:6px; color:#f2ca89; background:#362a1a; font-size:9px; } .permission-detail { max-height:100px; overflow:auto; margin:8px 0; color:#8f99ad; white-space:pre-wrap; overflow-wrap:anywhere; font:10px ui-monospace,SFMono-Regular,Menlo,monospace; } .permission-hint { color:var(--muted2); font-size:10px; line-height:1.5; } .permission-actions { display:grid; grid-template-columns:1fr 1fr; gap:6px; margin-top:9px; } .permission-actions button { border:1px solid var(--line); border-radius:7px; padding:6px; color:#bec5d3; background:#1a2030; font-size:10px; } .permission-actions .reject { color:#ff99a7; background:#2b1820; border-color:#4b2630; } .permission-actions .always { grid-column:1/-1; }
    .empty { padding:18px 8px; color:var(--muted2); text-align:center; font-size:11px; line-height:1.6; } .notice { position:fixed; left:50%; bottom:22px; z-index:20; max-width:min(520px,calc(100% - 32px)); transform:translate(-50%,16px); opacity:0; pointer-events:none; padding:10px 13px; border:1px solid #343b50; border-radius:10px; color:#d9deea; background:#171d29f2; box-shadow:0 14px 50px #0008; font-size:12px; transition:.2s ease; } .notice.show { opacity:1; transform:translate(-50%,0); } .notice.error { color:#ffabb7; border-color:#63303c; background:#2b1820f2; } .dev-note { color:var(--muted2); font-size:10px; line-height:1.6; } .dev-note a { color:#9f94f7; }
    @media(max-width:1080px){.shell{grid-template-columns:250px minmax(0,1fr) 280px}} @media(max-width:850px){body{overflow:auto}.app{height:auto;min-height:100%}.shell{grid-template-columns:220px minmax(0,1fr);min-height:calc(100vh - 58px)}.rightbar{display:none}} @media(max-width:650px){.brand small,.server-pill span:last-child{display:none}.shell{display:block}.sidebar{max-height:280px;border-right:0;border-bottom:1px solid var(--line)}.chat{min-height:calc(100vh - 58px)}.messages{padding-inline:16px}.agent-state{display:none}}
  </style>
</head>
<body>
  <div class="app">
    <header class="topbar"><div class="brand"><span class="brand-mark">AT</span><span>Agent Teams <small>for OpenCode</small></span></div><div class="server-pill"><span class="dot ${input.ready ? "ready" : ""}"></span><span>${input.ready ? "运行正常" : "尚未就绪"} · OpenCode ${version}</span></div></header>
    <div class="shell">
      <aside class="sidebar">
        <section class="section"><div class="section-head"><span class="eyebrow">新团队</span></div><form id="create-form"><input id="title" name="title" value="商品损益排查" aria-label="团队名称" required><button class="primary wide" type="submit">创建 Agent Team</button></form></section>
        <section class="section"><div class="section-head"><span class="eyebrow">最近任务</span><button class="icon-button" id="refresh-history" type="button" title="刷新">↻</button></div><div class="task-list" id="history-list"></div></section>
        <section class="section" id="agent-section" hidden><div class="section-head"><span class="eyebrow">Agent 团队</span></div><div class="agent-list" id="worker-list"></div></section>
      </aside>
      <main class="chat" id="workspace">
        <header class="chat-head"><div class="chat-title"><h1 id="agent-name">创建一个 Agent Team</h1><p id="agent-meta">把完整任务交给主 Agent，团队编排由它负责</p></div><div class="chat-actions"><span class="agent-state" id="agent-state"><span class="dot"></span><span>未选择</span></span><button class="icon-button" id="refresh" type="button" title="刷新聊天">↻</button><button class="danger-button" id="abort" type="button" disabled>停止</button></div></header>
        <div class="messages" id="messages" aria-live="polite"><div class="welcome"><div class="welcome-mark">✦</div><h2>只需告诉主 Agent 你的目标</h2><p>主 Agent 会自行判断是否需要 Worker、创建几个、如何分工，并持续监督它们。Worker 出现后，你也可以随时进入它的对话。</p></div></div>
        <div class="composer-wrap"><form class="composer" id="message-form"><textarea id="message" required disabled placeholder="选择一个 Agent 后开始对话…"></textarea><div class="composer-foot"><span id="message-label">Enter 换行 · ⌘/Ctrl + Enter 发送</span><button class="send" type="submit" disabled>发送</button></div></form></div>
      </main>
      <aside class="rightbar"><section class="section"><div class="section-head"><span class="eyebrow">权限中心</span><span class="count" id="permission-count">0</span></div><div class="permission-list" id="permission-list"><div class="empty">当前没有等待人工处理的权限。</div></div></section><section class="section"><div class="section-head"><span class="eyebrow">运行说明</span></div><div class="dev-note">页面会持续同步消息、工具调用、Agent 状态和错误。即使实时事件短暂断开，后台轮询也会继续更新。<br><br><a href="/health">查看服务健康状态</a><br>任务和审计记录保存在本地 SQLite。</div></section></aside>
    </div>
  </div>
  <div class="notice" id="notice"></div>
  <script>
    const state={taskGroupId:localStorage.getItem("oc-task-group-id"),agentId:localStorage.getItem("oc-agent-id"),title:localStorage.getItem("oc-task-title"),currentGroup:null,remoteMessages:[],optimistic:[],noticeTimer:null,refreshBusy:false,historyTick:0}
    const el=(selector)=>document.querySelector(selector)
    const createForm=el("#create-form"),messageForm=el("#message-form"),messages=el("#messages"),notice=el("#notice"),agentName=el("#agent-name"),agentMeta=el("#agent-meta"),agentState=el("#agent-state"),messageInput=el("#message"),messageLabel=el("#message-label"),sendButton=messageForm.querySelector("button"),abortButton=el("#abort"),workerList=el("#worker-list"),historyList=el("#history-list"),permissionList=el("#permission-list"),permissionCount=el("#permission-count")
    function setNotice(text,error=false){clearTimeout(state.noticeTimer);notice.textContent=text;notice.className="notice show"+(error?" error":"");state.noticeTimer=setTimeout(()=>{notice.className="notice"},error?6500:3200)}
    async function api(path,options={}){const response=await fetch(path,{...options,headers:{"content-type":"application/json",...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error?.message||"请求失败：HTTP "+response.status);return body}
    function roleName(agent){if(!agent)return"Agent";if(agent.role==="MAIN")return"主 Agent";if(agent.role==="APPROVER")return"权限审批 Agent";return agent.name}
    function roleCode(agent){return agent.role==="MAIN"?"MAIN":agent.role==="APPROVER"?"PA":"W"}
    function statusText(status){return({READY:"就绪",RUNNING:"运行中",WAITING_APPROVAL:"等待权限",IDLE:"空闲",FAILED:"失败",CANCELLED:"已停止",CREATING:"创建中"})[status]||status||"未知"}
    function activeAgent(){return(state.currentGroup?.agents||[]).find((agent)=>agent.id===state.agentId)}
    function updateAgentHeader(agent){if(!agent)return;agentName.textContent=state.title+" · "+roleName(agent);agentMeta.textContent="Session "+agent.opencodeSessionId+(agent.lastError?" · "+agent.lastError:"");agentState.replaceChildren();const dot=document.createElement("span");dot.className="dot "+agent.lifecycleStatus;const text=document.createElement("span");text.textContent=statusText(agent.lifecycleStatus);agentState.append(dot,text);abortButton.disabled=!["RUNNING","WAITING_APPROVAL","READY","IDLE"].includes(agent.lifecycleStatus);messageInput.disabled=false;sendButton.disabled=false;messageInput.placeholder="发送消息给"+roleName(agent)+"…";messageLabel.textContent="正在与"+roleName(agent)+"对话 · ⌘/Ctrl + Enter 发送"}
    function setActiveAgent(taskGroup,agent){state.taskGroupId=taskGroup.id;state.agentId=agent.id;state.title=taskGroup.title;state.remoteMessages=[];state.optimistic=[];localStorage.setItem("oc-task-group-id",state.taskGroupId);localStorage.setItem("oc-agent-id",state.agentId);localStorage.setItem("oc-task-title",state.title);el("#agent-section").hidden=false;updateAgentHeader(agent)}
    function formatTime(info){const value=info?.time?.created||info?.createdAt;if(!value)return"";const date=new Date(typeof value==="number"?value:String(value));return Number.isNaN(date.getTime())?"":date.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}
    function safeJson(value){if(value===undefined)return"";if(typeof value==="string")return value;try{return JSON.stringify(value,null,2)}catch{return String(value)}}
    function errorText(error){if(!error)return"";if(typeof error==="string")return error;return error?.data?.message||error?.message||error?.name||safeJson(error)}
    function textOfMessage(item){return(item?.parts||[]).filter((part)=>part?.type==="text"&&typeof part.text==="string").map((part)=>part.text).join("\\n")}
    function createToolCard(part){const value=part.state||{},status=value.status||"pending",card=document.createElement("div");card.className="tool-card";const head=document.createElement("div");head.className="tool-head";const title=document.createElement("span");title.textContent="⌁ "+(part.tool||part.name||"工具调用");const badge=document.createElement("span");badge.className="tool-status "+status;badge.textContent=({pending:"准备中",running:"执行中",completed:"已完成",error:"失败"})[status]||status;head.append(title,badge);const detail=document.createElement("pre");detail.className="tool-detail";const toolInput=value.input??part.input,output=value.output??value.content??part.output,failure=value.error;detail.textContent=[toolInput===undefined?"":"输入\\n"+safeJson(toolInput),output===undefined?"":"输出\\n"+safeJson(output),failure===undefined?"":"错误\\n"+errorText(failure)].filter(Boolean).join("\\n\\n")||"等待工具返回…";card.append(head,detail);return card}
    function createTurn(item,optimistic=false){const role=item?.info?.role||"assistant",turn=document.createElement("article");turn.className="turn "+(role==="user"?"user":"assistant");const avatar=document.createElement("div");avatar.className="turn-avatar";avatar.textContent=role==="user"?"YOU":"AI";const body=document.createElement("div");body.className="turn-body";const meta=document.createElement("div");meta.className="turn-meta";meta.textContent=(role==="user"?"你":roleName(activeAgent()))+(optimistic?" · 发送中":formatTime(item.info)?" · "+formatTime(item.info):"");body.append(meta);let visible=0;for(const part of item?.parts||[]){if(part?.type==="text"&&typeof part.text==="string"&&part.text!==""){const bubble=document.createElement("div");bubble.className="bubble";bubble.textContent=part.text;body.append(bubble);visible+=1}else if(part?.type==="reasoning"&&typeof part.text==="string"&&part.text!==""){const reasoning=document.createElement("details");reasoning.className="reasoning";const summary=document.createElement("summary");summary.textContent="查看思考过程";const content=document.createElement("div");content.textContent=part.text;reasoning.append(summary,content);body.append(reasoning);visible+=1}else if(part?.type==="tool"){body.append(createToolCard(part));visible+=1}}const failure=errorText(item?.info?.error);if(failure){const error=document.createElement("div");error.className="message-error";error.textContent="OpenCode 运行失败："+failure;body.append(error);visible+=1}if(visible===0&&role==="assistant"){const thinking=document.createElement("div");thinking.className="thinking";thinking.innerHTML="<i></i><i></i><i></i><span>正在思考或等待工具…</span>";body.append(thinking)}turn.append(avatar,body);return turn}
    function renderMessages(items){const nearBottom=messages.scrollHeight-messages.scrollTop-messages.clientHeight<120,remoteTexts=new Set((items||[]).filter((item)=>item?.info?.role==="user").map(textOfMessage));state.optimistic=state.optimistic.filter((item)=>!remoteTexts.has(textOfMessage(item)));messages.replaceChildren();const all=[...(items||[]).map((item)=>({item,optimistic:false})),...state.optimistic.map((item)=>({item,optimistic:true}))];if(!all.length){const welcome=document.createElement("div");welcome.className="welcome";welcome.innerHTML="<div class=\\"welcome-mark\\">✦</div><h2>开始和这个 Agent 对话</h2><p>消息会实时显示，包含工具调用、执行状态、权限等待和错误信息。</p>";messages.append(welcome)}else for(const entry of all)messages.append(createTurn(entry.item,entry.optimistic));const agent=activeAgent();if(agent?.lifecycleStatus==="RUNNING"&&!all.some((entry)=>entry.item?.info?.role==="assistant"&&!entry.item?.info?.time?.completed))messages.append(createTurn({info:{role:"assistant"},parts:[]}));if(nearBottom||state.optimistic.length)messages.scrollTop=messages.scrollHeight}
    function renderAgents(group){state.currentGroup=group;workerList.replaceChildren();for(const agent of (group.agents||[]).filter((candidate)=>candidate.role!=="APPROVER")){const button=document.createElement("button");button.type="button";button.className="agent-item"+(agent.id===state.agentId?" active":"");const avatar=document.createElement("span");avatar.className="avatar "+agent.role;avatar.textContent=roleCode(agent);const copy=document.createElement("span"),name=document.createElement("div"),role=document.createElement("div");name.className="agent-name";name.textContent=roleName(agent);role.className="agent-role";role.textContent=statusText(agent.lifecycleStatus);copy.append(name,role);const side=document.createElement("span"),open=agent.role==="MAIN"?(group.agentQuestions||[]).filter((question)=>question.status==="OPEN").length:0;if(open){side.className="question-count";side.textContent=String(open)}else side.className="dot "+agent.lifecycleStatus;button.append(avatar,copy,side);button.addEventListener("click",async()=>{setActiveAgent(group.taskGroup,agent);renderAgents(group);renderMessages([]);await refreshMessages()});workerList.append(button)}const active=activeAgent();if(active)updateAgentHeader(active)}
    function renderHistory(items){historyList.replaceChildren();if(!items.length){historyList.innerHTML="<div class=\\"empty\\">还没有任务</div>";return}for(const group of items){const button=document.createElement("button");button.type="button";button.className="task-item"+(group.taskGroup.id===state.taskGroupId?" active":"");const icon=document.createElement("span");icon.className="task-icon";icon.textContent="TG";const copy=document.createElement("span");copy.className="task-copy";const title=document.createElement("div");title.className="task-title";title.textContent=group.taskGroup.title;const meta=document.createElement("div");meta.className="task-meta";const workers=(group.agents||[]).filter((agent)=>agent.role==="WORKER").length;meta.textContent=workers+" 个 Worker · "+new Date(group.taskGroup.updatedAt).toLocaleDateString();copy.append(title,meta);button.append(icon,copy);button.addEventListener("click",async()=>{const main=(group.agents||[]).find((agent)=>agent.id===group.taskGroup.rootAgentId);if(!main)return;state.currentGroup=group;setActiveAgent(group.taskGroup,main);renderAgents(group);renderHistory(items);await Promise.all([refreshMessages(),refreshPermissions()])});historyList.append(button)}}
    function renderPermissions(items){permissionList.replaceChildren();permissionCount.textContent=String(items.length);if(!items.length){permissionList.innerHTML="<div class=\\"empty\\">当前没有等待人工处理的权限。</div>";return}for(const permission of items){const item=document.createElement("div");item.className="permission-item";const head=document.createElement("div");head.className="permission-title";const agent=(state.currentGroup?.agents||[]).find((candidate)=>candidate.id===permission.agentId);const title=document.createElement("span");title.textContent=roleName(agent)+" · "+permission.action;const risk=document.createElement("span");risk.className="risk";risk.textContent=permission.risk;head.append(title,risk);const detail=document.createElement("div");detail.className="permission-detail";detail.textContent=(permission.resources||[]).join("\\n")||safeJson(permission.metadata)||"没有附带资源信息";const hint=document.createElement("div");hint.className="permission-hint";hint.textContent=permission.reviewRequested?"审批 Agent 正在审核，你也可以直接接管。":"等待你处理。";const actions=document.createElement("div");actions.className="permission-actions";for(const option of [["once","允许一次",""],["reject","拒绝","reject"],["always","本任务始终允许","always"]]){const button=document.createElement("button");button.type="button";button.className=option[2];button.textContent=option[1];button.addEventListener("click",async()=>{for(const child of actions.querySelectorAll("button"))child.disabled=true;try{await api("/api/permissions/"+encodeURIComponent(permission.id)+"/decision",{method:"POST",body:JSON.stringify({decision:option[0]})});setNotice("权限已处理："+option[1]);await Promise.all([refreshPermissions(),refreshGroup()])}catch(error){setNotice(error.message,true);for(const child of actions.querySelectorAll("button"))child.disabled=false}});actions.append(button)}item.append(head,detail,hint,actions);permissionList.append(item)}}
    async function refreshHistory(){const body=await api("/api/task-groups");renderHistory(body.items||[])}
    async function refreshGroup(){if(!state.taskGroupId)return;const groupId=state.taskGroupId,group=await api("/api/task-groups/"+encodeURIComponent(groupId));if(groupId!==state.taskGroupId)return;const active=(group.agents||[]).find((agent)=>agent.id===state.agentId)||(group.agents||[]).find((agent)=>agent.id===group.taskGroup.rootAgentId);if(!active)throw new Error("Agent not found");state.currentGroup=group;state.agentId=active.id;renderAgents(group);return group}
    async function refreshMessages(){if(!state.agentId)return;const agentId=state.agentId;try{const body=await api("/api/agents/"+encodeURIComponent(agentId)+"/messages");if(agentId!==state.agentId)return;state.remoteMessages=body.items||[];renderMessages(state.remoteMessages);if(body.agent)updateAgentHeader(body.agent);if(body.warning)setNotice(body.warning,true)}catch(error){setNotice(error.message,true)}}
    async function refreshPermissions(){const query=state.taskGroupId?"&task_group_id="+encodeURIComponent(state.taskGroupId):"",body=await api("/api/permissions?status=PENDING"+query);renderPermissions(body.items||[])}
    async function refreshWorkspace(){if(state.refreshBusy||!state.agentId)return;state.refreshBusy=true;try{await Promise.all([refreshGroup(),refreshMessages(),refreshPermissions()]);state.historyTick+=1;if(state.historyTick%6===0)await refreshHistory()}catch(error){setNotice(error.message,true)}finally{state.refreshBusy=false}}
    createForm.addEventListener("submit",async(event)=>{event.preventDefault();const button=createForm.querySelector("button");button.disabled=true;setNotice("正在创建 Agent Team…");try{const title=el("#title").value.trim(),body=await api("/api/task-groups",{method:"POST",body:JSON.stringify({title})});state.currentGroup={taskGroup:body.taskGroup,agents:[body.agent,body.approver],workerTasks:[],agentQuestions:[]};setActiveAgent(body.taskGroup,body.agent);renderAgents(state.currentGroup);renderMessages([]);await refreshHistory();messageInput.focus();setNotice("团队已创建。直接把完整任务交给主 Agent 即可。")}catch(error){setNotice(error.message,true)}finally{button.disabled=false}})
    messageForm.addEventListener("submit",async(event)=>{event.preventDefault();if(!state.agentId)return;const text=messageInput.value.trim();if(!text)return;const agentId=state.agentId,optimistic={info:{id:"local-"+Date.now(),role:"user",time:{created:Date.now()}},parts:[{type:"text",text}]};state.optimistic.push(optimistic);messageInput.value="";renderMessages(state.remoteMessages);sendButton.disabled=true;setNotice("消息已发送，OpenCode 正在处理。");try{await api("/api/agents/"+encodeURIComponent(agentId)+"/messages",{method:"POST",body:JSON.stringify({text})});await refreshWorkspace()}catch(error){state.optimistic=state.optimistic.filter((item)=>item!==optimistic);messageInput.value=text;renderMessages(state.remoteMessages);setNotice(error.message,true)}finally{sendButton.disabled=false;messageInput.focus()}})
    messageInput.addEventListener("keydown",(event)=>{if(event.key==="Enter"&&(event.metaKey||event.ctrlKey)){event.preventDefault();messageForm.requestSubmit()}})
    el("#refresh").addEventListener("click",refreshWorkspace);el("#refresh-history").addEventListener("click",()=>refreshHistory().catch((error)=>setNotice(error.message,true)))
    abortButton.addEventListener("click",async()=>{if(!state.agentId)return;abortButton.disabled=true;try{await api("/api/agents/"+encodeURIComponent(state.agentId)+"/abort",{method:"POST",body:"{}"});setNotice("已停止当前 Agent 的运行。");await refreshWorkspace()}catch(error){setNotice(error.message,true)}})
    let eventTimer;const eventSource=new EventSource("/api/events"),scheduleRefresh=()=>{clearTimeout(eventTimer);eventTimer=setTimeout(refreshWorkspace,120)};for(const name of ["opencode.event","agent.message.accepted","worker.started","worker.failed","permission.requested","permission.resolved","permission.awaiting_human","agent_question.created","agent_question.answered","agent.supervisor_message"])eventSource.addEventListener(name,scheduleRefresh);eventSource.onerror=()=>setNotice("实时连接正在重连，轮询同步仍在继续。",true)
    setInterval(refreshWorkspace,1500);refreshHistory().catch((error)=>setNotice(error.message,true));refreshPermissions().catch(()=>{})
    if(state.taskGroupId&&state.agentId)refreshGroup().then(()=>Promise.all([refreshMessages(),refreshPermissions()])).catch(()=>{state.taskGroupId=null;state.agentId=null;localStorage.removeItem("oc-task-group-id");localStorage.removeItem("oc-agent-id");setNotice("之前的任务不存在，请重新创建或从列表选择。",true)})
  </script>
</body>
</html>`
}
